# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YItYEZHSJ6Tvie2eT4vTjjVl2ZPNbNxx
"""

from bs4 import BeautifulSoup
import requests

ipl_page=requests.get('https://www.cricbuzz.com/cricket-series/2810/indian-premier-league-2019/stats')

ipl_page

soup1=BeautifulSoup(ipl_page.text,'html')

ipl_codes=soup1.find('select',class_='form-control cb-cursor-pointer ng-pristine ng-untouched ng-valid ng-not-empty',id_='seasons')

ipl_codes

a=open('values_data.txt')

text_data=a.read()

text_data

import re

pattern=r'\d{4}'

ipl_codesandyears=re.findall(pattern,text_data)

ipl_code_dict=dict()
for i in range(0,len(ipl_codesandyears),2):
  ipl_code_dict[ipl_codesandyears[i+1]]=ipl_codesandyears[i]

for i in list(ipl_code_dict.keys()):
  if int(i)<2014:
    del ipl_code_dict[i]

years=list(ipl_code_dict.keys())
values=list(ipl_code_dict.values())

years

values

list_0f_df=[]
for k in range(len(ipl_code_dict)):
  ipl_scoreboard=(requests.get("https://www.cricbuzz.com/cricket-series/"+
                                     values[k]+"/indian-premier-league-"+years[k]+"/points-table"))
  scr_brd=BeautifulSoup(ipl_scoreboard.text,'html')
  scr_brd_tble=scr_brd.find('table',class_='table cb-srs-pnts')
  other_data=scr_brd_tble.find_all('td',class_="cb-srs-pnts-td")
  entire_data=[data.text for data in other_data]
  names=scr_brd_tble.find_all('td',class_='cb-srs-pnts-name')
  teams=[name_data.text for name_data in names]
  cols=scr_brd_tble.find_all('td',class_='cb-srs-pnts-th')
  columns=[data.text for data in cols]
  columns.append('Teams')
  columns=columns[-1:]+columns[:-1]
  columns.append('points')
  columns[-2],columns[-1]=columns[-1],columns[-2]
  df=pd.DataFrame(columns=columns)
  df['Teams']=teams
  j=0
  for i in range(len(teams)):
    ind=1
    while(1):
      df.iloc[i,ind]=entire_data[j]
      try:
        int(entire_data[j])
      except:
        j+=1
        break
      j+=1
      ind+=1
  list_0f_df.append(df)

list_0f_df=list_0f_df[::-1]
years=years[::-1]
for dfs in range(len(list_0f_df)):
  print("Year",years[dfs],"\n")
  display(list_0f_df[dfs])
  print("\n")

